[package]
name = "sparsevec"
version = "0.1.0"
edition = "2021"
authors = ["Ryo Nakabayashi <ryonakabayashi@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "*"
itertools = "*"
petgraph = "*"
